import React, { useMemo, useState } from 'react';
import { USERS, ROLE_META, SD_PROJECTS, SD_BOQ, SD_DWR, SD_DPR, SD_MAT, SD_TXN, SD_INDENTS, SD_LABOUR, SD_ISSUES, SD_SUBCON, SD_VENDOR_LEDGER, SD_VENDOR_DB, SD_ORDERS } from '../constants';
import { lsG, lsS, useStore } from '../store';
import { fmtD, fmtINR, fmtN } from '../utils';
import { useToast } from './Toast';
import { Badge, Btn, Card, Inp } from './UI';

type Store = { key: string; label: string; icon: string; value: any[]; setValue: (value: any) => void };
type User = { username: string; password: string; name: string; role: string; avatar: string; active?: boolean; lastLogin?: string; createdAt?: number };

const NAV = [['overview', 'Overview', 'ti-dashboard'], ['users', 'Users', 'ti-users'], ['projects', 'Projects', 'ti-building'], ['boq', 'BOQ', 'ti-list-numbers'], ['dwr', 'Daily Work (DWR)', 'ti-clipboard'], ['dpr', 'Daily Progress (DPR)', 'ti-trending-up'], ['mat', 'Materials', 'ti-cube'], ['txn', 'Transactions', 'ti-arrows-shuffle'], ['indents', 'Indents', 'ti-package'], ['labour', 'Labour', 'ti-users-group'], ['issues', 'Issues', 'ti-alert-triangle'], ['subcon', 'Subcontractor Ledger', 'ti-address-book'], ['vendorLedger', 'Vendor Ledger', 'ti-businessplan'], ['vendorDB', 'Vendors', 'ti-id-badge-2'], ['orders', 'Orders', 'ti-truck-delivery'], ['settings', 'Settings', 'ti-settings']] as const;
const names: Record<string, string> = Object.fromEntries(NAV.map(([key, label]) => [key, label]));

export function AdminPage() {
  const { showToast } = useToast();
  const [admin, setAdmin] = useState<User | null>(null);
  const [section, setSection] = useState('overview');
  const [projectId, setProjectId] = useState<number | null>(null);
  const [menuOpen, setMenuOpen] = useState(true);
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [users, setUsers] = useState<User[]>(() => lsG('users', USERS));
  const [projects, setProjects] = useStore('projects', SD_PROJECTS); const [boq, setBoq] = useStore('boq', SD_BOQ); const [dwr, setDwr] = useStore('dwr', SD_DWR); const [dpr, setDpr] = useStore('dpr', SD_DPR); const [mat, setMat] = useStore('mat', SD_MAT); const [txn, setTxn] = useStore('txn', SD_TXN); const [indents, setIndents] = useStore('indents', SD_INDENTS); const [labour, setLabour] = useStore('labour', SD_LABOUR); const [issues, setIssues] = useStore('issues', SD_ISSUES); const [subcon, setSubcon] = useStore('subconLedger', SD_SUBCON); const [vendorLedger, setVendorLedger] = useStore('vendorLedger', SD_VENDOR_LEDGER); const [vendorDB, setVendorDB] = useStore('vendorDB', SD_VENDOR_DB); const [orders, setOrders] = useStore('orders', SD_ORDERS);
  const stores: Store[] = [
    { key: 'projects', label: 'Projects', icon: 'ti-building', value: projects, setValue: setProjects }, { key: 'boq', label: 'BOQ', icon: 'ti-list-numbers', value: boq, setValue: setBoq }, { key: 'dwr', label: 'DWR', icon: 'ti-clipboard', value: dwr, setValue: setDwr }, { key: 'dpr', label: 'DPR', icon: 'ti-trending-up', value: dpr, setValue: setDpr }, { key: 'mat', label: 'Materials', icon: 'ti-cube', value: mat, setValue: setMat }, { key: 'txn', label: 'Transactions', icon: 'ti-arrows-shuffle', value: txn, setValue: setTxn }, { key: 'indents', label: 'Indents', icon: 'ti-package', value: indents, setValue: setIndents }, { key: 'labour', label: 'Labour', icon: 'ti-users-group', value: labour, setValue: setLabour }, { key: 'issues', label: 'Issues', icon: 'ti-alert-triangle', value: issues, setValue: setIssues }, { key: 'subcon', label: 'Subcontractor Ledger', icon: 'ti-address-book', value: subcon, setValue: setSubcon }, { key: 'vendorLedger', label: 'Vendor Ledger', icon: 'ti-businessplan', value: vendorLedger, setValue: setVendorLedger }, { key: 'vendorDB', label: 'Vendors', icon: 'ti-id-badge-2', value: vendorDB, setValue: setVendorDB }, { key: 'orders', label: 'Orders', icon: 'ti-truck-delivery', value: orders, setValue: setOrders },
  ];
  const login = () => { const found = users.find(user => user.username === username.trim() && user.password === password && user.role === 'admin' && user.active !== false); if (!found) return showToast('Invalid administrator credentials', 'error'); setAdmin(found); showToast('Administrator access granted'); };
  if (!admin) return <div className="blueprint-bg admin-login-page"><Card className="admin-login-card" style={{ width: 'min(440px, 100%)', padding: 32 }}><div className="admin-eyebrow">RESTRICTED ADMIN ROUTE · /admin</div><h1>Administrator sign in</h1><p>Access every project, module, user, and database record.</p><Inp value={username} onChange={(event: any) => setUsername(event.target.value)} placeholder="Admin username" /><div className="admin-login-gap" /><Inp type="password" value={password} onChange={(event: any) => setPassword(event.target.value)} placeholder="Admin password" onKeyDown={(event: any) => event.key === 'Enter' && login()} /><div className="admin-login-gap" /><Btn full onClick={login} icon="ti-lock-open">Open admin panel</Btn></Card></div>;
  const updateUsers = (next: User[]) => { setUsers(next); lsS('users', next); };
  return <div className={`admin-shell ${menuOpen ? 'admin-nav-open' : ''}`}><div className={`mobile-overlay ${menuOpen ? 'open' : ''}`} onClick={() => setMenuOpen(false)} /><aside className={`admin-sidebar ${menuOpen ? 'open' : ''}`}><div className="admin-brand"><strong>SITETRACK PRO</strong><span>ADMIN CONTROL</span><button onClick={() => setMenuOpen(false)} aria-label="Close admin menu"><i className="ti ti-x" /></button></div><nav>{NAV.map(([key, label, icon]) => <button key={key} className={section === key ? 'active' : ''} onClick={() => { setSection(key); setProjectId(null); setMenuOpen(false); }}><i className={`ti ${icon}`} />{label}</button>)}</nav></aside><main className="admin-main"><header className="admin-topbar"><button className="admin-menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle admin menu"><i className={`ti ${menuOpen ? 'ti-layout-sidebar-left-collapse' : 'ti-menu-2'}`} /></button><strong>SITETRACK PRO - ADMIN</strong><div className="admin-identity"><Badge text={admin.username} color="#ec4899" /><Btn sm variant="ghost" icon="ti-logout" onClick={() => setAdmin(null)}>Sign out</Btn></div></header><div className="admin-content">{section === 'overview' && <Overview stores={stores} users={users} onProject={(id: number) => { setProjectId(id); setSection('projects'); }} />}{section === 'users' && <UsersPanel users={users} updateUsers={updateUsers} showToast={showToast} />}{section === 'projects' && <ProjectPanel projects={projects} projectId={projectId} onSelect={setProjectId} stores={stores} showToast={showToast} />}{!['overview', 'users', 'projects'].includes(section) && <DatasetPanel dataset={stores.find(store => store.key === section) || stores[0]} projects={projects} showToast={showToast} />}{section === 'settings' && <SettingsPanel showToast={showToast} />}</div></main></div>;
}

function Overview({ stores, users, onProject }: { stores: Store[]; users: User[]; onProject: (id: number) => void }) { return <><PageTitle title="Overview" subtitle="Live database overview and project access" /><div className="admin-stat-grid">{stores.map(store => <div className="admin-stat" key={store.key}><i className={`ti ${store.icon}`} /><strong>{store.value.length}</strong><span>{store.label}</span></div>)}</div><div className="admin-overview-grid"><Card><h2>Projects and module scope</h2>{stores[0].value.map(project => <button className="admin-project-row" key={project.id} onClick={() => onProject(project.id)}><span><strong>{project.name}</strong><small>{project.location} · {project.client}</small></span><i className="ti ti-arrow-right" /></button>)}</Card><Card><h2>User accounts</h2>{users.map(user => <div className="user-row" key={user.username}><Badge text={ROLE_META[user.role]?.label || user.role} color={ROLE_META[user.role]?.color || '#9ca3af'} /><span>{user.name}<small>@{user.username}</small></span><em>{user.active === false ? 'Inactive' : 'Active'}</em></div>)}</Card><Card><h2>System health</h2><div className="health-value"><strong>{stores.reduce((sum, store) => sum + store.value.length, 0)}</strong><span>Total records</span></div><div className="health-value"><strong>{stores.filter(store => !store.value.length).length}</strong><span>Empty modules</span></div></Card></div></>; }

function ProjectPanel({ projects, projectId, onSelect, stores, showToast }: { projects: any[]; projectId: number | null; onSelect: (id: number | null) => void; stores: Store[]; showToast: any }) { const project = projects.find(item => item.id === projectId); if (!project) return <><PageTitle title="Projects" subtitle="Select a project to inspect every related module" /><div className="admin-project-grid">{projects.map(item => <button className="admin-project-card" key={item.id} onClick={() => onSelect(item.id)}><i className="ti ti-building" /><strong>{item.name}</strong><span>{item.location} · {item.client}</span><small>Open project workspace</small></button>)}</div></>; const scoped = stores.filter(store => store.key !== 'projects').map(store => ({ ...store, value: store.value.filter(item => item.projectId === projectId) })); return <><button className="admin-back-button" onClick={() => onSelect(null)}><i className="ti ti-arrow-left" /> All projects</button><PageTitle title={project.name} subtitle={`${project.location} · ${project.client} · ${project.status || 'Active'}`} /><div className="admin-stat-grid">{scoped.map(store => <div className="admin-stat" key={store.key}><i className={`ti ${store.icon}`} /><strong>{store.value.length}</strong><span>{store.label}</span></div>)}</div><div className="project-module-grid">{scoped.map(store => <Card key={store.key}><h2>{store.label} <Badge text={`${store.value.length}`} color="#f97316" /></h2><ReadableTable dataset={store} projects={projects} showToast={showToast} /></Card>)}</div></>; }

function DatasetPanel({ dataset, projects, showToast }: { dataset: Store; projects: any[]; showToast: any }) { const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [asc, setAsc] = useState(true); const filtered = useMemo(() => dataset.value.filter(item => readable(item, projects).toLowerCase().includes(query.toLowerCase())).sort((a, b) => readable(a, projects).localeCompare(readable(b, projects)) * (asc ? 1 : -1)), [dataset.value, projects, query, asc]); const pageSize = 10; const shown = filtered.slice((page - 1) * pageSize, page * pageSize); return <><PageTitle title={dataset.label} subtitle={`Readable ${dataset.label.toLowerCase()} records`}/><div className="admin-toolbar"><Inp value={query} onChange={(event: any) => { setQuery(event.target.value); setPage(1); }} placeholder={`Search ${dataset.label.toLowerCase()}...`} /><Btn variant="ghost" onClick={() => setAsc(!asc)} icon="ti-arrows-sort">Sort</Btn><span>Showing {filtered.length ? (page - 1) * pageSize + 1 : 0}-{Math.min(page * pageSize, filtered.length)} of {filtered.length}</span></div><Card><ReadableTable dataset={{ ...dataset, value: shown }} projects={projects} showToast={showToast} /><div className="pagination"><Btn sm variant="ghost" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</Btn><span>Page {page} of {Math.max(1, Math.ceil(filtered.length / pageSize))}</span><Btn sm variant="ghost" disabled={page >= Math.ceil(filtered.length / pageSize)} onClick={() => setPage(page + 1)}>Next</Btn></div></Card></>; }

function ReadableTable({ dataset, projects, showToast }: { dataset: Store; projects: any[]; showToast: any }) { const remove = (id: any) => { if (!window.confirm('Delete this record?')) return; dataset.setValue((items: any[]) => items.filter(item => item.id !== id)); showToast(`${dataset.label} record deleted`); }; const columns = columnsFor(dataset.key); return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>#</th>{columns.map(column => <th key={column.key}>{column.label}</th>)}<th>Actions</th></tr></thead><tbody>{dataset.value.map((item, index) => <tr key={item.id || index}><td>{index + 1}</td>{columns.map(column => <td key={column.key}>{column.render(item, projects)}</td>)}<td><Btn sm variant="danger" icon="ti-trash" onClick={() => remove(item.id)}>Delete</Btn></td></tr>)}</tbody></table>{!dataset.value.length && <div className="admin-empty">No records in this module</div>}</div>; }

function columnsFor(key: string) { const text = (field: string) => ({ key: field, label: field.replace(/[A-Z]/g, letter => ` ${letter}`).toUpperCase(), render: (item: any) => item[field] ?? '-' }); const project = { key: 'project', label: 'PROJECT', render: (item: any, projects: any[]) => projects.find(projectItem => projectItem.id === item.projectId)?.name || '-' }; if (key === 'projects') return [text('name'), text('location'), text('client'), text('status'), { key: 'budget', label: 'BUDGET', render: (item: any) => fmtINR(item.budget) }]; if (key === 'boq') return [project, text('item'), text('unit'), { key: 'qty', label: 'QTY / DONE', render: (item: any) => `${fmtN(item.boqQty)} / ${fmtN(item.cumDone)}` }, { key: 'rate', label: 'RATE', render: (item: any) => fmtINR(item.rate) }]; if (key === 'dwr') return [text('date'), project, text('description'), text('location'), text('workStatus')]; if (key === 'dpr') return [text('date'), project, text('description'), text('qtyDone'), text('pct'), text('workStatus')]; if (key === 'mat') return [text('name'), text('unit'), text('opening'), text('minStock'), text('supplier')]; if (key === 'txn') return [text('date'), project, text('material'), text('type'), text('qty'), text('ref')]; if (key === 'indents') return [text('date'), project, text('urgency'), text('status'), { key: 'items', label: 'ITEMS', render: (item: any) => item.items?.length || 0 }]; if (key === 'labour') return [text('date'), project, text('subcon'), text('shift'), text('count'), text('hours'), { key: 'cost', label: 'COST', render: (item: any) => fmtINR(item.cost) }]; if (key === 'issues') return [text('date'), project, text('title'), text('category'), text('priority'), text('status')]; if (key === 'subcon' || key === 'vendorLedger') return [text('date'), project, text(key === 'subcon' ? 'subcon' : 'vendor'), text('type'), { key: 'amount', label: 'AMOUNT', render: (item: any) => fmtINR(item.amount) }, { key: 'paid', label: 'PAID', render: (item: any) => fmtINR(item.paid) }]; if (key === 'vendorDB') return [text('name'), text('company'), text('mobile'), text('category'), text('location')]; if (key === 'orders') return [text('date'), project, text('vendor'), text('material'), text('orderedQty'), text('billStatus'), text('payStatus')]; return [text('name'), text('date'), text('description')]; }

function readable(item: any, projects: any[]) { return Object.values(item).map(value => typeof value === 'object' ? '' : String(value)).join(' ') + ' ' + (projects.find(project => project.id === item.projectId)?.name || ''); }
function UsersPanel({ users, updateUsers, showToast }: { users: User[]; updateUsers: (users: User[]) => void; showToast: any }) { const [form, setForm] = useState({ name: '', username: '', password: '', role: 'engineer' }); const add = () => { if (!form.name || !form.username || form.password.length < 6) return showToast('Enter all fields; password must be 6+ characters', 'error'); if (users.some(user => user.username === form.username.trim())) return showToast('Username already exists', 'error'); updateUsers([...users, { ...form, username: form.username.trim(), avatar: form.name.slice(0, 2).toUpperCase(), active: true, createdAt: Date.now() }]); setForm({ name: '', username: '', password: '', role: 'engineer' }); showToast('User created'); }; return <><PageTitle title="Users" subtitle="Manage accounts and access status" /><Card><div className="admin-form-grid"><Inp value={form.name} onChange={(event: any) => setForm({ ...form, name: event.target.value })} placeholder="Display name" /><Inp value={form.username} onChange={(event: any) => setForm({ ...form, username: event.target.value })} placeholder="Username" /><Inp type="password" value={form.password} onChange={(event: any) => setForm({ ...form, password: event.target.value })} placeholder="Password" /><select value={form.role} onChange={event => setForm({ ...form, role: event.target.value })}>{Object.entries(ROLE_META).map(([role, meta]) => <option key={role} value={role}>{meta.label}</option>)}</select><Btn onClick={add} icon="ti-user-plus">Add user</Btn></div></Card><Card><AdminTable headers={['Name', 'Username', 'Role', 'Status', 'Actions']}><tbody>{users.map(user => <tr key={user.username}><td>{user.name}</td><td>@{user.username}</td><td><Badge text={ROLE_META[user.role]?.label || user.role} color={ROLE_META[user.role]?.color} /></td><td>{user.active === false ? 'Inactive' : 'Active'}</td><td><Btn sm variant="ghost" onClick={() => updateUsers(users.map(item => item.username === user.username ? { ...item, active: item.active === false } : item))}>{user.active === false ? 'Activate' : 'Deactivate'}</Btn></td></tr>)}</tbody></AdminTable></Card></>; }
function SettingsPanel({ showToast }: { showToast: any }) { return <><PageTitle title="Settings" subtitle="Shared configuration and database controls" /><Card><h2>System settings</h2><p style={{ color: 'var(--t2)', fontSize: 13 }}>Work categories, units, issue categories, and subcontractors are managed from the application constants.</p><Btn variant="danger" onClick={() => showToast('Database reset requires explicit confirmation', 'warning')} icon="ti-alert-triangle">Danger zone</Btn></Card></>; }
function PageTitle({ title, subtitle }: { title: string; subtitle: string }) { return <div className="admin-page-title"><div className="admin-eyebrow">SITETRACK PRO · ADMIN</div><h1>{title}</h1><p>{subtitle}</p></div>; }
function AdminTable({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="admin-table-wrap"><table className="admin-table"><thead><tr>{headers.map(header => <th key={header}>{header}</th>)}</tr></thead>{children}</table></div>; }
