import React, { useState } from 'react';
import * as XLSX from 'xlsx';
import { Badge, PBar, Btn, Lbl, Sel, TH, TD } from './UI';
import { today, fmtD, fmtN, fmtINR } from '../utils';
import { ROLE_META, ucol } from '../constants';

export function QMSReports({ user, projects, dpr, boq, labour, issues, showToast }: any) {
  const [selP, setSelP] = useState(projects[0]?.id || 0);
  const proj = projects.find((p: any) => p.id === +selP);
  
  const pBoq = boq.filter((b: any) => b.projectId === +selP && !b.isExtra);
  const pExtra = boq.filter((b: any) => b.projectId === +selP && b.isExtra);
  const pDpr = dpr.filter((d: any) => d.projectId === +selP);
  const pLabour = labour.filter((l: any) => l.projectId === +selP);
  const pIssues = issues.filter((i: any) => i.projectId === +selP);
  
  const totalLabour = pLabour.reduce((s: any, l: any) => s + l.count, 0);
  const openIssues = pIssues.filter((i: any) => i.status === "Open").length;
  const pct = pBoq.length ? Math.round(pBoq.reduce((s: any, i: any) => s + i.cumDone, 0) / pBoq.reduce((s: any, i: any) => s + i.boqQty, 0) * 100) : 0;
  const doneVal = pBoq.reduce((s: any, b: any) => s + b.cumDone * b.rate, 0);
  const cfItems = pDpr.filter((r: any) => r.carryForward);
  const canGenerate = user.role === "qms" || user.role === "md" || user.role === "admin";

  const exportExcel = () => {
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet([
      { Field: "Project", Value: proj?.name || "-" },
      { Field: "Location", Value: proj?.location || "-" },
      { Field: "Client", Value: proj?.client || "-" },
      { Field: "Generated On", Value: new Date().toLocaleString("en-IN") },
      { Field: "Generated By", Value: user.name },
      { Field: "Overall BOQ Progress", Value: pct + "%" },
      { Field: "Work Done Value", Value: fmtINR(doneVal) },
      { Field: "DPR Entries", Value: pDpr.length },
      { Field: "Total Labour Days", Value: totalLabour },
      { Field: "Open Issues", Value: openIssues },
      { Field: "Carry Forward Items", Value: cfItems.length }
    ]), "Summary");
    
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(pBoq.map((b: any) => ({
      Item: b.item, Unit: b.unit, "BOQ Qty": b.boqQty, "Done": b.cumDone, "Balance": b.boqQty - b.cumDone, Rate: b.rate, "Done Value": b.cumDone * b.rate, "% Done": Math.round(b.cumDone / b.boqQty * 100) + "%"
    }))), "BOQ Progress");
    
    if (pExtra.length) XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(pExtra.map((b: any) => ({
      Item: b.item, Unit: b.unit, "Qty": b.boqQty, "Done": b.cumDone, Rate: b.rate
    }))), "Extra Items");
    
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(pDpr.map((r: any, i: number) => ({
      "#": i + 1, Date: r.date, Description: r.description, "% Done": r.pct + "%", "Qty Done": r.qtyDone, "Work Status": r.workStatus || "-", "Carry Forward": r.carryForward ? "Yes" : "No", Engineer: r.engineer, Reason: r.reason || "-"
    }))), "DPR");
    
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(pLabour.map((l: any, i: number) => ({
      "#": i + 1, Date: l.date, Trade: l.trade, Count: l.count, Subcon: l.subcon, Shift: l.shift
    }))), "Labour");
    
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(pIssues.map((i: any, n: number) => ({
      "#": n + 1, Date: i.date, Title: i.title, Category: i.category, Priority: i.priority, Status: i.status, "Assigned": i.assignedTo, "Resolved": i.resolvedDate || "-"
    }))), "Issues");
    
    XLSX.writeFile(wb, "SiteTrack_Report_" + proj?.name?.replace(/\s+/g, "_") + "_" + today() + ".xlsx");
    showToast("Report exported!");
  };

  const printReport = () => {
    const html = `<!DOCTYPE html><html><head><title>SiteTrack QMS Report</title><style>body{font-family:Arial;padding:24px;color:#1e293b;font-size:11px}h1{color:#fb923c;font-size:20px;margin-bottom:4px}h2{color:#0f172a;font-size:14px;margin:18px 0 8px;border-bottom:2px solid #fb923c;padding-bottom:4px}.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:18px}.kpi{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:10px;text-align:center}.kpi .val{font-size:20px;font-weight:800;color:#fb923c}.kpi .lbl{font-size:9px;color:#64748b;font-weight:700;text-transform:uppercase}table{width:100%;border-collapse:collapse;margin-bottom:14px}th{background:#fb923c;color:#fff;padding:6px 8px;text-align:left;font-size:10px}td{padding:5px 8px;border-bottom:1px solid #e2e8f0;font-size:10px}tr:nth-child(even) td{background:#f8fafc}.badge{display:inline-block;padding:2px 7px;border-radius:12px;font-size:9px;font-weight:700}.ok{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:#92400e}.red{background:#fee2e2;color:#991b1b}.cf{background:#fef9c3;color:#713f12}</style></head><body>
    <h1>SiteTrack Pro — QMS Report</h1>
    <p style="color:#64748b;margin-bottom:16px"><strong>Project:</strong> ${proj?.name || "-"} &nbsp;|&nbsp; <strong>Client:</strong> ${proj?.client || "-"} &nbsp;|&nbsp; <strong>Location:</strong> ${proj?.location || "-"} &nbsp;|&nbsp; <strong>Date:</strong> ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })} &nbsp;|&nbsp; <strong>Prepared by:</strong> ${user.name} (${ROLE_META[user.role].label})</p>
    <div class="kpis"><div class="kpi"><div class="val">${pct}%</div><div class="lbl">BOQ Progress</div></div><div class="kpi"><div class="val">${fmtINR(doneVal)}</div><div class="lbl">Done Value</div></div><div class="kpi"><div class="val">${pDpr.length}</div><div class="lbl">DPR Entries</div></div><div class="kpi"><div class="val">${totalLabour}</div><div class="lbl">Labour Days</div></div><div class="kpi"><div class="val">${openIssues}</div><div class="lbl">Open Issues</div></div></div>
    <h2>BOQ Progress</h2>
    <table><thead><tr><th>#</th><th>Work Item</th><th>Unit</th><th>BOQ Qty</th><th>Completed</th><th>Balance</th><th>% Done</th></tr></thead><tbody>${pBoq.map((b: any, i: number) => { const p = Math.round(b.cumDone / b.boqQty * 100); const cls = p >= 100 ? "ok" : p >= 60 ? "warn" : "red"; return `<tr><td>${i + 1}</td><td>${b.item}</td><td>${b.unit}</td><td>${b.boqQty}</td><td>${b.cumDone}</td><td>${b.boqQty - b.cumDone}</td><td><span class="badge ${cls}">${p}%</span></td></tr>`; }).join("")}</tbody></table>
    ${pExtra.length ? `<h2>Extra Items (Client Variations)</h2><table><thead><tr><th>#</th><th>Item</th><th>Unit</th><th>Qty</th><th>Done</th><th>Rate</th></tr></thead><tbody>${pExtra.map((b: any, i: number) => `<tr><td>${i + 1}</td><td>⭐ ${b.item}</td><td>${b.unit}</td><td>${b.boqQty}</td><td>${b.cumDone}</td><td>${fmtINR(b.rate)}</td></tr>`).join("")}</tbody></table>` : ""}
    <h2>Daily Progress Report</h2>
    <table><thead><tr><th>Date</th><th>Description</th><th>% Done</th><th>Qty Done</th><th>Status</th><th>CF</th><th>Engineer</th><th>Reason</th></tr></thead><tbody>${pDpr.map((r: any) => `<tr><td>${r.date}</td><td>${r.description}</td><td>${r.pct}%</td><td>${r.qtyDone}</td><td>${r.workStatus || "-"}</td><td>${r.carryForward ? '<span class="badge cf">CF</span>' : "-"}</td><td>${r.engineer}</td><td>${r.reason || "-"}</td></tr>`).join("")}</tbody></table>
    ${cfItems.length ? `<h2>Carry Forward Items (${cfItems.length})</h2><table><thead><tr><th>Date</th><th>Description</th><th>% Done</th><th>Reason</th></tr></thead><tbody>${cfItems.map((r: any) => `<tr><td>${r.date}</td><td>${r.description}</td><td>${r.pct}%</td><td>${r.reason || "-"}</td></tr>`).join("")}</tbody></table>` : ""}
    <h2>Open Issues</h2>
    <table><thead><tr><th>Date</th><th>Title</th><th>Category</th><th>Priority</th><th>Assigned To</th></tr></thead><tbody>${pIssues.filter((i: any) => i.status === "Open").map((i: any) => `<tr><td>${i.date}</td><td>${i.title}</td><td>${i.category}</td><td>${i.priority}</td><td>${i.assignedTo}</td></tr>`).join("") || "<tr><td colspan='5' style='text-align:center;color:#10b981'>No open issues</td></tr>"}</tbody></table>
    <p style="color:#94a3b8;font-size:9px;margin-top:20px;border-top:1px solid #e2e8f0;padding-top:10px">Generated by SiteTrack Pro &nbsp;|&nbsp; ${new Date().toLocaleString("en-IN")}</p>
    </body></html>`;
    const w = window.open("", "_blank");
    w?.document.write(html);
    w?.document.close();
    setTimeout(() => w?.print(), 400);
    showToast("Report opened for printing!");
  };

  return (
    <div className="fadeIn">
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20, flexWrap: "wrap", gap: 12 }}>
        <div><div style={{ fontSize: 26, fontWeight: 800 }}>QMS Reports</div><div style={{ color: "var(--t2)", fontSize: 13, marginTop: 3 }}>Generate project progress reports — print PDF or export Excel</div></div>
        {!canGenerate && <Badge text="QMS & MD Only" color="var(--t3)" icon="ti-lock" />}
      </div>
      
      <div style={{ display: "grid", gridTemplateColumns: "1fr auto auto", gap: 12, marginBottom: 22, alignItems: "end" }}>
        <div><Lbl>Select Project</Lbl><Sel value={selP} onChange={(e: any) => setSelP(+e.target.value)}>{projects.map((p: any) => <option key={p.id} value={p.id}>{p.name}</option>)}</Sel></div>
        <Btn icon="ti-file-type-pdf" variant="danger" onClick={printReport} disabled={!canGenerate}>Print / PDF</Btn>
        <Btn icon="ti-file-spreadsheet" variant="success" onClick={exportExcel} disabled={!canGenerate}>Export Excel</Btn>
      </div>

      <div style={{ background: "var(--s1)", border: "2px solid var(--br2)", borderRadius: 16, overflow: "hidden" }}>
        <div style={{ background: "linear-gradient(135deg, rgba(251,146,60,0.15), rgba(251,146,60,0.05))", padding: "20px 26px", borderBottom: "1px solid var(--br)" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
            <div>
              <div style={{ fontSize: 10, color: "var(--t3)", fontWeight: 700, letterSpacing: "0.1em", marginBottom: 4 }}>SITETRACK PRO — QMS REPORT</div>
              <div style={{ fontSize: 20, fontWeight: 800, marginBottom: 3 }}>{proj?.name || "—"}</div>
              <div style={{ fontSize: 12, color: "var(--t2)" }}>{proj?.client || "-"} · {proj?.location || "-"} · {new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}</div>
            </div>
            <div style={{ textAlign: "right" }}>
              <div style={{ fontSize: 11, color: "var(--t3)" }}>Prepared by</div>
              <div style={{ fontWeight: 700, fontSize: 14 }}>{user.name}</div>
              <div style={{ fontSize: 11, color: ROLE_META[user.role].color }}>{ROLE_META[user.role].label}</div>
            </div>
          </div>
        </div>
        <div style={{ padding: "20px 26px" }}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: 12, marginBottom: 22 }}>
            {[
              { lbl: "BOQ Progress", val: pct + "%", color: "#fb923c", icon: "ti-chart-bar" },
              { lbl: "Done Value", val: fmtINR(doneVal), color: "#10b981", icon: "ti-coins" },
              { lbl: "DPR Entries", val: pDpr.length, color: "#3b82f6", icon: "ti-trending-up" },
              { lbl: "Labour Days", val: totalLabour, color: "#a78bfa", icon: "ti-users" },
              { lbl: "Open Issues", val: openIssues, color: openIssues > 0 ? "#ef4444" : "#10b981", icon: "ti-alert-triangle" }
            ].map(k => (
              <div key={k.lbl} style={{ background: "var(--s2)", border: "1px solid var(--br)", borderRadius: 10, padding: "14px", textAlign: "center" }}>
                <i className={"ti " + k.icon} style={{ fontSize: 18, color: k.color, display: "block", marginBottom: 5 }} />
                <div style={{ fontSize: 18, fontWeight: 900, color: k.color }}>{k.val}</div>
                <div style={{ fontSize: 9.5, color: "var(--t3)", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", marginTop: 3 }}>{k.lbl}</div>
              </div>
            ))}
          </div>
          
          {cfItems.length > 0 && (
            <div style={{ background: "rgba(251,191,36,0.08)", border: "1px solid rgba(251,191,36,0.3)", borderRadius: 10, padding: "12px 16px", marginBottom: 18, display: "flex", alignItems: "center", gap: 10 }}>
              <i className="ti ti-arrow-forward-up" style={{ fontSize: 18, color: "#fbbf24" }} />
              <div><strong style={{ color: "#fbbf24" }}>{cfItems.length} Carry Forward items</strong> — work delayed from planned dates</div>
            </div>
          )}

          <div style={{ fontWeight: 700, fontSize: 13, marginBottom: 12, display: "flex", alignItems: "center", gap: 7 }}><i className="ti ti-list-numbers" style={{ color: "#fb923c" }} />BOQ Progress</div>
          <table style={{ width: "100%", borderCollapse: "collapse", marginBottom: 20 }}>
            <thead><tr>{["Work Item", "Unit", "BOQ Qty", "Completed", "Balance", "% Done"].map(h => <TH key={h} c={h} />)}</tr></thead>
            <tbody>
              {pBoq.map((b: any) => {
                const p = Math.round(b.cumDone / b.boqQty * 100);
                const c = p >= 100 ? "#10b981" : p >= 60 ? "#fbbf24" : "#ef4444";
                return (
                  <tr key={b.id}>
                    <TD bold>{b.item}</TD><TD color="var(--t2)">{b.unit}</TD><TD mono>{fmtN(b.boqQty)}</TD><TD mono bold color="#10b981">{fmtN(b.cumDone)}</TD><TD mono bold color={b.boqQty - b.cumDone > 0 ? "#ef4444" : "var(--t3)"}>{fmtN(b.boqQty - b.cumDone)}</TD>
                    <td style={{ padding: "11px 13px", borderBottom: "1px solid var(--br)" }}><div style={{ display: "flex", alignItems: "center", gap: 8 }}><div style={{ width: 80 }}><PBar pct={p} color={c} /></div><span style={{ fontWeight: 700, color: c, fontSize: 12, minWidth: 32 }}>{p}%</span></div></td>
                  </tr>
                );
              })}
              {pExtra.length > 0 && <tr><td colSpan={6} style={{ padding: "8px 13px", background: "rgba(251,191,36,0.06)", fontSize: 11, fontWeight: 700, color: "#fbbf24" }}>⭐ Extra Items</td></tr>}
              {pExtra.map((b: any) => (
                <tr key={b.id}>
                  <TD bold color="#fbbf24">⭐ {b.item}</TD><TD color="var(--t2)">{b.unit}</TD><TD mono>{fmtN(b.boqQty)}</TD><TD mono bold color="#10b981">{fmtN(b.cumDone)}</TD><TD mono bold color="var(--t3)">{fmtN(b.boqQty - b.cumDone)}</TD><TD>{b.cumDone > 0 ? Math.round(b.cumDone / b.boqQty * 100) + "%" : "—"}</TD>
                </tr>
              ))}
            </tbody>
          </table>

          {pIssues.filter((i: any) => i.status === "Open").length > 0 && (
            <div>
              <div style={{ fontWeight: 700, fontSize: 13, marginBottom: 12, display: "flex", alignItems: "center", gap: 7 }}><i className="ti ti-alert-triangle" style={{ color: "#ef4444" }} />Open Issues</div>
              <table style={{ width: "100%", borderCollapse: "collapse" }}>
                <thead><tr>{["Date", "Title", "Category", "Priority", "Assigned To"].map(h => <TH key={h} c={h} />)}</tr></thead>
                <tbody>
                  {pIssues.filter((i: any) => i.status === "Open").map((i: any) => (
                    <tr key={i.id}><TD>{fmtD(i.date)}</TD><TD bold>{i.title}</TD><TD><Badge text={i.category} color="var(--t3)" /></TD><TD><Badge text={i.priority} color={ucol[i.priority]} /></TD><TD>{i.assignedTo}</TD></tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
